### ISSUE TITLE
peppypedia: todo checklist

### ISSUE THREAD

**Issue by WindowsMeosu** [WindowsMeosu/peppypedia#70]
- [ ] cleanup: delete unused or otherwise useless files, and also remove unnecessary stuff in markdown files
- [ ] transition to more a markdown-based style (tables, etc. are handled with html at the moment for most pages)
- [ ] automatic theme (just the docs and future themes)
- [ ] incorporate an api-like system (which would be limited)
- [ ] workflow for checkouts
- [ ] display authors and contributors before page headers
